name: rust cargo run
description: Rust Cargo Run

inputs:
  command:
    description: The cargo command to execute
    required: true
  args:
    description: The arguments to provide for the cargo command
    required: false
  components:
    description: The components to include when installing Rust
    required: false
  github_token:
    description: Github Token
    required: true
  save_cache:
    description: Whether to save the SSCACHE
    required: false
  cache_name:
    description: The name of the cache to save/restore
    required: true
    default: test

runs:
  using: composite
  steps:
  - name: Read rust-toolchain
    id: rust
    run: echo "toolchain=$(cat rust-toolchain)" >> $GITHUB_OUTPUT
    shell: bash
  - name: Installing Rust
    uses: dtolnay/rust-toolchain@master
    with:
      toolchain: ${{ steps.rust.outputs.toolchain }}
      components: ${{ inputs.components }}
  - name: Setting up cache
    uses: pl-strflt/rust-sccache-action@v1
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
      SCCACHE_CACHE_SIZE: 2G
      SCCACHE_DIR: ${{ github.workspace }}/.cache/sccache
      CACHE_SKIP_SAVE: ${{ inputs.save_cache == '' || inputs.save_cache == 'false' }}
    with:
      version: v0.2.15
      shared-key: v1-${{ inputs.cache_name }}  # change this to invalidate sccache for this job
  - name: Running ${{ inputs.command }}
    env:
      CARGO_INCREMENTAL: '0'
    run: cargo ${{ inputs.command }} ${{ inputs.args }}
    shell: bash
