name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Installing Rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        components: rustfmt
    - name: Running fmt
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: fmt
        args: -- --check

  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Installing Rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        components: clippy
    - name: Code Lint
      uses: ./.github/actions/rust-cargo-run
      with:
        command: clippy
        args: --all-targets --all-features --workspace -- -D warnings
        github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Running tests
      uses: ./.github/actions/rust-cargo-run
      with:
        command: test
        args: --all --no-fail-fast
        github_token: ${{ secrets.GITHUB_TOKEN }}
        save_cache: true
