name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v3
    - name: Installing Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Running fmt
      run: cargo fmt -- --check

  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v3
    - name: Installing Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Code Lint
      uses: ./.github/actions/rust-cargo-run
      with:
        command: clippy
        args: --all-targets --all-features --workspace -- -D warnings
        github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v3
    - name: Running tests
      uses: ./.github/actions/rust-cargo-run
      with:
        command: test
        args: --all --no-fail-fast
        github_token: ${{ secrets.GITHUB_TOKEN }}
        save_cache: true
